config/routes.rb
Rails.application.routes.draw do
  root to: 'event#index'

  resources :event
  resources :user
  devise_for :users
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/attendance.rb
class Attendance < ApplicationRecord
	belongs_to :user
	belongs_to :event
end

app/models/event.rb
class Event < ApplicationRecord
	has_many :attendances
	has_many :users, through: :attendances

	validate :date_cannot_be_in_the_past
	validate :multiple_of_five
	validates :title, presence: true, length: { in: 5..140 }
	validates :description, presence: true, length: { in: 20..1000 }
	validates :price, presence: true, numericality: { only_integer: true, in: 1..1000 }
	validates :location, presence: true

	def date_cannot_be_in_the_past
 	   if !start_date.present? || start_date < Date.today
 	     errors.add(:start_date, "can't be in the past")
 	   end
	end

	def multiple_of_five
 	   if !duration.present? || duration % 5 != 0 || duration <= 0
 	     errors.add(:duration, "not a multiple of 5 or the number is negativ")
 	   end
	end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  after_create :welcome_send
	has_many :attendances
	has_many :events, through: :attendances

  def welcome_send
    UserMailer.welcome_email(self).deliver_now
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/event_controller.rb
class EventController < ApplicationController
  before_action :authenticate_user!, only: [:new, :create]
  def index
    @events = Event.all
  end
  def new
    @event = Event.new
  end
  def create
    @event = Event.new()
    if @event.save
      redirect_to event_path(@event.id)
    else
      flash.now[:danger] = "L'évenement n'a pas pu être créé !"
      render :new
    end
  end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def index
  end

  def secret
  end
end

app/controllers/user_controller.rb
class UserController < ApplicationController
  before_action :authenticate_user!, only: [:show]
  def new
  end

  def show
    @user = current_user
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/event_helper.rb
module EventHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/helpers/user_helper.rb
module UserHelper
end

app/views/event/index.html.erb
<div class="jumbotron">
	<div class="container">
		<h1 class="display-3">Hello, world!</h1>
		<p>This is a template for a simple marketing or informational website. It includes a large callout called a
			jumbotron and three supporting pieces of content. Use it as a starting point to create something more
			unique.</p>

      <% if user_signed_in? %>
		<%= link_to "Créer un événement", new_event_path, :class=>"btn btn-lg btn-success" %>
      <% end %>
	</div>

</div>
<div class="container">
	<div class="row">
    <% @events.each do |event| %>
		<div class="col-sm-6" style="padding: 15px;">
		<div class="card">
          <div class="card-header">
            <h2><%= event.title %></h2>
          </div>
          <div class="card-body">
            <p class="text"><%= event.description%></p>
				<div class="row">
					<div class="col-sm-6">
					<table class="table table-hover">
						<tr class="table-secondary">
							<th>Début</th>
							<td><%= event.start_date.ctime%></td>
						</tr>
						<tr class="table-light">
							<th>Durée</th>
							<td><%= event.duration%> min</td>
						</tr>
					</table>
					</div>
					<div class="col-sm-6">
					<table class="table table-hover">
						<tr class="table-secondary">
							<th>Prix</th>
							<td><%= event.price%> €</td>
						</tr>
						<tr class="table-light">
							<th>Lieux</th>
							<td><%= event.location%></td>
						</tr>
					</table>
          			</div>
          		</div>
        	</div>
		</div>
		</div>
		<% end %>
	</div>
</div>

app/views/event/new.html.erb
<div class="container" style="border-radius: 5px;">
	<div class="row justify-content-center">
		<div class="card">
        	<h3 class="card-header text-center">Créer un événement</h3>
    		<div class="card-body">
			<%= form_tag url_for(action: "create"), method: "post" do %>
				<div class="form-group">
					<label for="titre" class="form-label mt-4">Titre</label>
					<%= search_field_tag 'title', nil, class: "form-control" %>
				</div>
				<div class="form-group">
					<label for="contenu" class="form-label mt-4">Contenu</label>
					<%= text_area_tag 'content', nil, class: "form-control" %>
				</div>
				<div class="row justify-content-center">
					<%= submit_tag "Créer l'événement", class: "btn btn-primary", style: "width: 300px; margin-top: 20px;" %>
				</div>
   			</div>
			<% end %>
		</div>
	</div>
</div>

app/views/events/index.html.erb
<div class="jumbotron">
	<div class="container">
		<h1 class="display-3">Hello, world!</h1>
		<p>This is a template for a simple marketing or informational website. It includes a large callout called a
			jumbotron and three supporting pieces of content. Use it as a starting point to create something more
			unique.</p>
		<p><a class="btn btn-primary btn-lg" href="#" role="button">Learn more »</a></p>
	</div>

</div>
<div class="container">
	<div class="row">
    <% @events.each do |event| %>
		<div class="col-sm-6" style="padding: 15px;">
		<div class="card">
          <div class="card-header">
            <h2><%= event.title %></h2>
          </div>
          <div class="card-body">
            <p class="text"><%= event.description%></p>
				<div class="row">
					<div class="col-sm-6">
					<table class="table table-hover">
						<tr class="table-secondary">
							<th>Début</th>
							<td><%= event.start_date.ctime%></td>
						</tr>
						<tr class="table-light">
							<th>Durée</th>
							<td><%= event.duration%> min</td>
						</tr>
					</table>
					</div>
					<div class="col-sm-6">
					<table class="table table-hover">
						<tr class="table-secondary">
							<th>Prix</th>
							<td><%= event.price%> €</td>
						</tr>
						<tr class="table-light">
							<th>Lieux</th>
							<td><%= event.location%></td>
						</tr>
					</table>
          			</div>
          		</div>
        	</div>
		</div>
		</div>
		<% end %>
	</div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>EventProject</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
  <nav class="navbar navbar-expand-lg navbar-light bg-light fixed-top">
  <div class="container-fluid">
    <a class="navbar-brand" href="#">Events Project</a>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarNavDropdown">
      <ul class="navbar-nav">
        <li class="nav-item">
						<%= link_to "Accueil", root_path, :class=>"nav-link active" %>
        </li>
      </ul>
    </div>
    <div class="">
      <% if user_signed_in? %>
  				<div class="btn-group" role="group">
  				<button id="btnGroupDrop1" type="button" class="btn btn-primary dropdown-toggle" data-bs-toggle="dropdown" aria-haspopup="true" aria-expanded="false"><%= current_user.email %></button>
    			<div class="dropdown-menu dropdown-menu-end">
					  <%= link_to "Profile", user_path(current_user.id), :class=>"dropdown-item" %>
					  <%= link_to "Se déconnecter", destroy_user_session_path, method: :delete, :class=>"dropdown-item" %>
    			</div>
				<% else %>
				<div class="btn-group" role="group">
  				<button id="btnGroupDrop1" type="button" class="btn btn-primary dropdown-toggle" data-bs-toggle="dropdown" aria-haspopup="true" aria-expanded="false">Connexion</button>
    			<div class="dropdown-menu dropdown-menu-end">
					  <%= link_to "Créé un compte", new_user_registration_path, :class=>"dropdown-item" %>
            <%= link_to "Se connecter", new_user_session_path, :class=>"dropdown-item" %>
    			</div>
				<% end %>
    </div>
  </div>
  </nav>
  <main role="main" class="container" style="margin-top: 30px;">
    <%= yield %>
  </main>
  <footer class="footer mt-auto text-center">
        <div class="row">
          <div class="col-lg-12">
            <p>Made by <a href="https://github.com/T-PRAT">Titouan Prat</a>.</p>
            <p>Based on <a href="https://getbootstrap.com/" rel="nofollow">Bootstrap</a>. Icons from <a href="https://fontawesome.com/" rel="nofollow">Font Awesome</a>. Web fonts from <a href="https://fonts.google.com/" rel="nofollow">Google</a>.</p>
          </div>
    </div>
  </footer>
  </body>
</html>

app/views/static_pages/index.html.erb
<ul>
  <% if user_signed_in? %>
    <li>
      <%= link_to "Sign out", destroy_user_session_path, method: :delete %>
    </li>

    <li>
      Voici ton email : <%= current_user.email %>
    </li>

    <li>
      <%= link_to "Secret page", static_pages_secret_path %>
    </li>

    <li>
      <%= link_to "Edit email / password", edit_user_registration_path %>
    </li>

  <% else %>
    <li>
      <%= link_to "Sign in", new_user_session_path %>
    </li>

    <li>
      <%= link_to "Sign up", new_user_registration_path %>
    </li>

  <% end %>
</ul>

app/views/static_pages/secret.html.erb
<h1>StaticPages#secret</h1>
<p>Find me in app/views/static_pages/secret.html.erb</p>

app/views/user/new.html.erb
<h1>User#new</h1>
<p>Find me in app/views/user/new.html.erb</p>

app/views/user/show.html.erb
<div class="container-xl" style="border-radius: 5px;">
	<div class="row justify-content-center">
		<div class="card" style="width: 50rem;">
			<div class="card-header text-center">
				<h3 class="title">Description de l'utilisateur</h3>
			</div>
			<div class="card-body">
				<table class="table table-hover text-muted">
					<tr class="table-primary">
						<th scope="row">Nom</th>
						<th><%= @user.last_name %></th>
					</tr>
					<tr class="table-light">
						<th scope="row">Prénom</th>
						<th><%= @user.first_name %></th>
					</tr>
					<tr class="table-primary">
						<th scope="row">email</th>
						<th><%= @user.email %></th>
					</tr>
					<tr class="table-light">
						<th scope="row">Description</th>
						<th><%= @user.description %></th>
					</tr>
					<tr>
						<th scope="row">Crée le</th>
						<th><%= @user.created_at %></th>
					</tr>
					<tr>
						<th scope="row">Derniere modification</th>
						<th><%= @user.updated_at %></th>
					</tr>
					</tr>
				</table>
				<div class="row">
				<div class="btn-group">
   	       			<%= link_to "Modifier ", edit_user_registration_path, :class=>"btn btn-lg btn-warning" %>
           			<%= link_to "Supprimer", cancel_user_registration_path, :class=>"btn btn-lg btn-danger" %>
				</div>
				</div>
			</div>
		</div>
	</div>
</div>